name: Generate RSS Feed

on:
  workflow_dispatch:  # Allow manual runs from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run generate_rss.py
        run: python generate_rss.py

      - name: Touch dummy file to force commit
        run: |
          date > touchfile.txt

      - name: Commit RSS feed and dummy file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git rebase origin/main || true
          git add debt_feed.xml touchfile.txt
          git commit -m "Update RSS feed [bot]" || echo "No changes to commit"
          git push origin HEAD:main || echo "Push failed — likely due to upstream update."
