name: Generate RSS

on:
  schedule:
    - cron: '30 * * * *'  # Run every hour on the half-hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run python generate_rss.py
      run: python generate_rss.py
